apiVersion: v1
kind: ServiceAccount
metadata:
  name: openshift-gitops-argocd-manager
  namespace: openshift-gitops

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-manager-role
  namespace: testapi
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-manager-role-binding
  namespace: testapi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-manager-role
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-manager
  namespace: openshift-gitops

---
oc -n openshift-gitops create -f - << EOF
apiVersion: v1
stringData:
  config: '{"bearerToken":"$(oc serviceaccounts get-token -n openshift-gitops openshift-gitops-argocd-manager)","tlsClientConfig":{"insecure":true}}'
  name: testapi
  namespaces: testapi
  server: https://kubernetes.default.svc
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: cluster
  name: cluster-kubernetes.default.svc-testapi
type: Opaque
EOF