apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testapi-app
  namespace: openshift-gitops
spec:
  project: default

  source:
    repoURL: https://gitlab.com/FaresHerhar/testapi-argocd.git
    targetRevision: HEAD
    path: manifests

  destination: 
    server: https://kubernetes.default.svc
    namespace: testapi

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
