apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://gitlab.com/FaresHerhar/testapi-argocd.git
  password: glpat-jFt6MRyQYCq7NHNPyE3k
  username: faresherhar
