apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://gitlab.com/FaresHerhar/testapi-argocd.git
  password: Z2xwYXQteXJmRWQ1dl9reU5lUktFd3FSVXY=
  username: faresherhar
