apiVersion: v1
kind: Secret
metadata:
  name: quay-pull-secret
  namespace: testapi
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJabUZ5WlhOb1pYSm9ZWElyY21WaFpHSnZkRG81VkVneU0waElSMUJNVEVWSlYwUlpTazFXTnpZeFFscEhWa2xGU1ZJM1JEWTJVbFpCTkZWU1VUUkhSMDFDTmt3elFVMUpXRUl4TUVvMldWSlhVRkZUIiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson
