apiVersion: v1
kind: Secret
metadata:
  name: quay-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJabWhsY21oaGNpdDBaV3QwYjI0Nk5UaEZWRWxTUWsxQ1drNVJSMGxOVDA1RVJsaFBObGRCVGpaT1YwdEtUVUpCVDFNM01FNVJOa0kzT1ZkYU5UQldTekZaTjFSWE9FeEdOVGt6UXpWRVN3PT0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://gitlab.com/FaresHerhar/testapi-argocd.git
  password: glpat-15AQvxRV-3rsGiUcdUDf
  username: faresherhar
