apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testapi-ingress
  namespace: testapi
spec:
  tls:
    - hosts:
        - testapi.apps.ocp4-9.infocepo.com
      secretName: testapi-tls
  rules:
    - host: testapi.apps.ocp4-9.infocepo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: testapi-service
                port:
                  number: 8080

    - host: nginx.apps.ocp4-9.infocepo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 8080
