apiVersion: v1
kind: Service
metadata:
  name: testapi-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8001
  selector:
    app: testapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapi-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testapi
  template:
    metadata:
      labels:
        app: testapi
    spec:
      containers:
      - image: faresherhar/testapi:python-3.9-slim
        name: testapi
        ports:
        - containerPort: 8001
